title: Bowery
email: support@bowery.io
name: Bowery
url: "http://bowery.io"
twitter_username: boweryio
github_username:  Bowery
markdown: kramdown
exclude: ["vendor"]
permalink: /:categories/:title
version: 0.0.0
gems:
  - jekyll-sitemap
