title: Bowery
email: support@bowery.io
name: Bowery
url: "http://bowery.io"
blogbaseurl: "/blog"
twitter_username: boweryio
github_username:  Bowery
markdown: kramdown
asset_pipeline:
  bundle: true
  compress: true
  output_path: static
  display_path: static
  gzip: true
